### PR TITLE
Remove Changes to Stock

### PR DESCRIPTION
**Pull request by DanStaal**
Remove the manipulation of the stock parts in the tech tree.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Discussion is needed, please.

**Comment by DanStaal** [comment]
Agreed.  ;)  I more put this in to make sure you knew where the changes were, and that there *were* changes.  I'm not entirely against them in principle, but I think they should be mentioned in the mod's description at the very least, and probably if included they should be in their own file.  Separation out into using PatchManager for this is probably good as well.

The remainder of this file should probably be integrated directly into the part's config files, in my opinion.

**Comment by linuxgurugamer** [comment]
The reason it's in a config is so that people can remove it and just have the parts appear in sandbox mod.

I will update the description, thanks for that.

**Comment by linuxgurugamer** [comment]
Can this be closed?

**Pull request closed without merging**
