### PR TITLE
Please review

### PR DESCRIPTION
**Pull request by Shaggygoblin**
Made some Updates/Tweaks/Fixes/.cfg's/MM.dll

### CODE REVIEW

**Comment by Shaggygoblin** [comment]
Keep all or some of it, or toss it out completely... cheers

**Comment by linuxgurugamer** [comment]
It will take me a few days, but I will review it
Thanks

**Comment by linuxgurugamer** [comment]
Please remove the ModuleManager dll totally

**Comment by Shaggygoblin** [comment]
This and sounding rockets were, to me, the perfect early game that just made sense... add in KAX, FS, or another 'early planes' mod and boom: very lightweight realistic early progression, starting with conceptual crafts using the SR's & 'make believe' with the BR's...  Saw one of my nieces sitting in a refrigerator box pretending it was a plane...  cheesy as it is, "KAD" (Kardboard Assisted Drafting) is essential, imho.

**Comment by Shaggygoblin** [comment]
attempting to use an old tool (DDS4KSP) to convert the .jpg/.png plywood tex to .dds...  testing now

**Comment by Shaggygoblin** [comment]
not sure why, in vanilla, the fins show with the correct plywood(chipboard) texture, but in my 'mega mods' install the squad texture remains...  i have texture replacer, ven's, and possibly other 'texture/model-changing' mods on that install that might be causing the *plywood.dds to not be applied.  I'm at a loss on this one...  but, the important bit is the *plywood.dds is correctly applied to the fins in a vanilla install...  vanilla = inside GameData is Squad, BargainRockets, and MM.2.8.1.dll

The Vanilla Result:
Vanilla Install


The Mega Mods Result:
Mega Mods Install

**Comment by linuxgurugamer** [comment]
Merging into a dev branch, but looks good.
Sorry it took so long, was lost in the forest.

**Pull request merged**
